#!/data/data/com.termux/files/usr/bin/bash

## Make a simple dialog to greet the users
dialog --title "Information" \
 --msgbox \
 "Welcome to ubdroid. an easy ubuntu installer. if you have problems. join my discord server. or make an issue in github\
  Learn more about ubuntu in https://wiki.ubuntu.com . \
  To Uninstall ubuntu. type 'ubdroid --uninstall'" \
 13 40

